In [1]:
import numpy as np

In [7]:
Z=np.array([[1,1,1,1,1],[-2,-1,0,1,2]]).T
Y=np.array([[5,3,4,2,1],[-3,-1,-1,2,3]]).T

In [14]:
inv=np.linalg.inv(np.dot(Z.T,Z))

In [46]:
beta=np.dot(inv,np.dot(Z.T,Y))
beta

array([[ 3. ,  0. ],
       [-0.9,  1.5]])

In [30]:
Y

array([[ 5, -3],
       [ 3, -1],
       [ 4, -1],
       [ 2,  2],
       [ 1,  3]])

In [29]:
Yh=np.dot(Z,beta)
Yh

array([[ 4.8, -3. ],
       [ 3.9, -1.5],
       [ 3. ,  0. ],
       [ 2.1,  1.5],
       [ 1.2,  3. ]])

In [28]:
eps=Y-Yh
eps

array([[ 0.2,  0. ],
       [-0.9,  0.5],
       [ 1. , -1. ],
       [-0.1,  0.5],
       [-0.2,  0. ]])

In [31]:
np.dot(eps.T,Yh)

array([[ 9.41469125e-16, -6.66133815e-16],
       [ 0.00000000e+00,  0.00000000e+00]])

In [32]:
np.dot(Yh.T,Yh)

array([[ 53.1, -13.5],
       [-13.5,  22.5]])

In [36]:
np.dot(eps.T,eps)/5

array([[ 0.38, -0.3 ],
       [-0.3 ,  0.3 ]])

In [45]:
sigma=(Y-np.dot(Z,beta))
sigma

array([[ 0.2,  0. ],
       [-0.9,  0.5],
       [ 1. , -1. ],
       [-0.1,  0.5],
       [-0.2,  0. ]])

In [38]:
z0=np.array([0.5, 0.5 ]).T

In [53]:
np.dot(np.dot(z0.T,np.linalg.inv(np.dot(Z.T,Z))),z0)*0.3*5/3

0.037500000000000006

In [55]:
np.dot(z0.T,beta.T[1].T)-(3*19*0.0375)**0.5

-0.7120191517213446

In [50]:
(3*19*0.0475)**0.5

1.6454482671904334